FROM golang:1.25.1 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

ARG DB_CONNECTION
ENV DB_CONNECTION=$DB_CONNECTION
ARG REDIS_CONNECTION
ENV REDIS_CONNECTION=$REDIS_CONNECTION
ARG ACCESS_TOKEN_SECRET
ENV ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET
ARG REFRESH_TOKEN_SECRET
ENV REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET

RUN go build -o clicker_api server.go
FROM ubuntu:latest
WORKDIR /root/
RUN apt update && apt install -y libc6
COPY --from=builder /app/clicker_api .
EXPOSE 1323
CMD ["./clicker_api"]
